### ISSUE TITLE
Улучшение относительно счётчика статей

### ISSUE THREAD

**Issue by krdprog** [sasha370/blog_HQ#3]
Строка:

https://github.com/sasha370/blog_HQ/blob/34aa48c04f06c4caf8c2eab19d2fd3681406deaa/app/views/categories/index.html.erb#L16

Лучше делать это через `counter_cache` - вот тут описано http://rusrails.ru/active-record-associations#counter_cache

Тогда за подсчётом количества статей не будет лишний раз лазить в базу данных. Для каждой категории будет записано в отдельном поле количество статей.

На репо набрёл случайно, не мог пройти мимо, сам тоже из НН.

**Comment by sasha370** [comment]
Привет. Да, спасибо, что напомнил про counter_cache )  Действительно намного полезнее использовать его
Это был один из первых учебных проектов.
Очень хороший блог, кстати )

**Comment by krdprog** [comment]
rusrails - это перевод документации на русский язык с официальной https://guides.rubyonrails.org/ ;-)
не всегда успевает по актуальности, но в основном точный перевод. кстати, опенсорс, можешь тоже сделать свой вклад и принести пользу сообществу, там репо открыто принимает правки ;)

**Comment by krdprog** [comment]
черкни мне, если есть интерес к рельсам.

**Comment by sasha370** [comment]
Это очень круто! Т.к. я сейчас заканчиваю обучение и надо набивать руку на opensource проектах, чтобы подготовиться к работе.

**Comment by sasha370** [comment]
А что именно по рельсам? Они мне интересны, т.к. все жизнь сейчас под них перестраиваю)
